In [2]:
import numpy as np 

### Task 1 - 1D array of numbers from 0 to 9

In [4]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array
#print(array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Task 2 - 3×3 NumPy array of all Boolean value Trues

In [ ]:
array1 = np.full((3,3),True,dtype=bool, order='F')
print(array1)

### Task 3 - Extract all odd numbers from array of 1-10

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]


### Task 4 - Replace all odd numbers in an array of 1-10 with the value -1

In [13]:
A = np.arange(16)
Z = A.reshape(4,4)
print("Before")
print(Z)
print("\nAfter")
Z[Z%2 == 1] = -1
print(Z)

Before
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After
[[ 0 -1  2 -1]
 [ 4 -1  6 -1]
 [ 8 -1 10 -1]
 [12 -1 14 -1]]


### Task 5 - Convert a 1D array to a 2D array with 2 rows

In [12]:
array1 = np.array([1,2,3,4])
print("Before")
print(array1)
arrayNew = array1.reshape(2,2)
print("\nAfter")
print(arrayNew)

Before
[1 2 3 4]

After
[[1 2]
 [3 4]]


### Task 6 - Create two arrays a and b, stack these two arrays vertically use the np.dot and 
np.sum to calculate total

In [14]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
c = np.dot(a, b)
d = np.sum(c)
#print(a)
#print(b)
print(c)
print('\n')
print(d)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


2079


### Task 7 - Create the following pattern array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])

In [27]:
arr=np.array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])
print(arr)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Task 8 - In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in arrays 

In [23]:
arr=np.array((1,2,3,4,5))
arr1=np.array((4,5,6,7,8,9))
print(arr,arr1)
new_array= np.concatenate((arr,arr1),axis=0)
np.unique(new_array)


[1 2 3 4 5] [4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Task 9 - Get all items between 3 and 7 from a and b and sum themtogether

In [38]:
arr=np.array((1,2,3,4,5))
arr1=np.array((4,5,6,7,8,9))
print(arr,arr1)
new_array= np.concatenate((arr,arr1),axis=0)
arr2=np.unique(new_array)
arr3=arr[3:7]
arr4=np.sum(arr3)
print("\n",arr2,"\n",arr3,"\n",arr4)


[1 2 3 4 5] [4 5 6 7 8 9]

 [1 2 3 4 5 6 7 8 9] 
 [4 5] 
 9
